### ISSUE TITLE
handle network offline more gracefully

### ISSUE THREAD

**Issue by genodeftest** [timlau/dnf-daemon#2]
Currently when starting yumex-dnf on an offline PC which has not been online since last boot, I get a huge error message dialog in yumex-dnf:
```
g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.dnf.exceptions.RepoError: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dnf/repo.py", line 206, in perform
    return super(_Handle, self).perform(result)
  File "/usr/lib64/python3.4/site-packages/librepo/__init__.py", line 1425, in perform
    _librepo.Handle.perform(self, result)
librepo.LibrepoException: (8, "Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f23&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]", 'An Curl handle error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dnf/repo.py", line 796, in load
    if self._try_revive():
  File "/usr/lib/python3.4/site-packages/dnf/repo.py", line 710, in _try_revive
    handle.perform()
  File "/usr/lib/python3.4/site-packages/dnf/repo.py", line 210, in perform
    raise _DetailedLibrepoError(exc, source)
dnf.repo._DetailedLibrepoError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/dbus/service.py", line 826, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.4/site-packages/dnfdaemon/server/__init__.py", line 83, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 207, in SetConfig
    rc = self.set_option(setting, value)
  File "/usr/lib/python3.4/site-packages/dnfdaemon/server/__init__.py", line 692, in set_option
    if hasattr(self.base.conf, option):
  File "/usr/lib/python3.4/site-packages/dnfdaemon/server/__init__.py", line 218, in base
    self._get_base()
  File "/usr/lib/python3.4/site-packages/dnfdaemon/server/__init__.py", line 1065, in _get_base
    self._base.setup_base()
  File "/usr/lib/python3.4/site-packages/dnfdaemon/server/backend.py", line 66, in setup_base
    self.fill_sack()
  File "/usr/lib/python3.4/site-packages/dnf/base.py", line 249, in fill_sack
    self._add_repo_to_sack(r.id)
  File "/usr/lib/python3.4/site-packages/dnf/base.py", line 104, in _add_repo_to_sack
    repo.load()
  File "/usr/lib/python3.4/site-packages/dnf/repo.py", line 817, in load
    raise dnf.exceptions.RepoError(msg)
dnf.exceptions.RepoError: Failed to synchronize cache for repo 'updates' from 'https://mirrors.fedoraproject.org/metalink?repo=updates-released-f23&arch=x86_64': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f23&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
 (36)
```
Please make this error message simpler and easier to understand for users.

**Comment by genodeftest** [comment]
This is a duplicate of timlau/yumex-dnf#59. Sorry for the noise.
